# The Atomic Mass Evaluation Sheet
This notebook was created to make an easier interface than the text file at https://www-nds.iaea.org/amdc/ame2016/mass16.txt. I will use it throughout my Nuclear Physics course.

## Preparing the Dataframe
To create the pandas datafram I had go through the text file line by line and create a list of lists and then I was able to create a dataframe out of that.

### Large Values At the End of the file
Looking at the very large nuclei at the end of the file (and dataframe) we can see that the first number is cut off. I am assuming this is because the format of the textfile moved it over later. Eventually I will fix this, but for now looking at the 'A' value it can be seen what that number should be.

In [1]:
import pandas as pd

titleList = []

whole_list = []

count = 0
f = open("mass16.txt", "r")
for line in f:
    if count == 37 :
        titleList.append(line[0:4].strip())
        titleList.append(line[8:9].strip())
        titleList.append(line[13:14].strip())
        titleList.append(line[17:18].strip())
        titleList.append(line[20:22].strip())
        titleList.append(line[26:27].strip())
        titleList.append(line[32:43].strip())
        titleList.append(line[50:66].strip())
        titleList.append(line[74:91].strip())
        titleList.append(line[100:111].strip())
    
        
        
    if count > 38 :
        newEntry = []
        newEntry.append(line[0:6].strip())
        newEntry.append(line[6:12].strip())
        newEntry.append(line[12:17].strip())
        newEntry.append(line[16:20].strip())
        newEntry.append(line[19:23].strip())
        newEntry.append(line[24:29].strip())
        newEntry.append(line[29:54].strip())
        newEntry.append(line[54:73].strip())
        newEntry.append(line[72:97].strip())
        newEntry.append(line[97:124].strip())
        
        whole_list.append(newEntry)
        
        
        
        
    
    count = count + 1

In [2]:
df = pd.DataFrame.from_records(whole_list, columns=titleList)

In [3]:
df

,1N-Z,N,Z,A,EL,O,MASS EXCESS,BINDING ENERGY/A,BETA-DECAY ENERGY,ATOMIC MASS
0,0 1,1,0,1,n,,8071.31713 0.00046,0.0 0.0,B- 782.347 0.000,1 008664.91582 0.00049
1,-1,0,1,1,H,,7288.97061 0.00009,0.0 0.0,B- *,1 007825.03224 0.00009
2,0 0,1,1,2,H,,13135.72176 0.00011,1112.283 0.000,B- *,2 014101.77811 0.00012
3,0 1,2,1,3,H,,14949.80993 0.00022,2827.265 0.000,B- 18.592 0.000,3 016049.28199 0.00023
4,-1,1,2,3,He,,14931.21793 0.00021,2572.680 0.000,B- -13736# 2000#,3 016029.32265 0.00022
5,-3,0,3,3,Li,-pp,28667# 2000#,-2267# 667#,B- *,3 030775# 2147#
6,0 2,3,1,4,H,-n,24621.127 100.000,1720.449 25.000,B- 22196.211 100.000,4 026431.868 107.354
7,0,2,2,4,He,,2424.91561 0.00006,7073.915 0.000,B- -22898.273 212.132,4 002603.25413 0.00006
8,-2,1,3,4,Li,-p,25323.189 212.132,1153.760 53.033,B- *,4 027185.562 227.733
9,0 3,4,1,5,H,-nn,32892.444 89.443,1336.359 17.889,B- 21661.211 91.652,5 035311.493 96.020
10,1,3,2,5,He,-n,11231.233 20.000,5512.132 4.000,B- -447.654 53.852,5 012057.224 21.470
11,-1,2,3,5,Li,-p,11678.886 50.000,5266.132 10.000,B- -25460# 2003#,5 012537.800 53.677
12,-3,1,4,5,Be,x,37139# 2003#,18# 401#,B- *,5 039870# 2150#
13,0 4,5,1,6,H,-3n,41875.721 254.127,961.639 42.354,B- 24283.626 254.127,6 044955.437 272.816
14,2,4,2,6,He,,17592.095 0.053,4878.519 0.009,B- 3505.216 0.053,6 018885.891 0.057
15,0,3,3,6,Li,,14086.87895 0.00144,5332.331 0.000,B- -4288.154 5.448,6 015122.88742 0.00155
16,-2,2,4,6,Be,-,18375.033 5.448,4487.247 0.908,B- -28945# 2003#,6 019726.409 5.848
17,-4,1,5,6,B,x,47320# 2003#,-467# 334#,B- *,6 050800# 2150#
18,0 5,6,1,7,H,-nn,49135# 1004#,940# 143#,B- 23062# 1004#,7 052749# 1078#
19,3,5,2,7,He,-n,26073.126 7.559,4123.057 1.080,B- 11166.021 7.559,7 027990.654 8.115
20,1,4,3,7,Li,,14907.10529 0.00423,5606.439 0.001,B- -861.893 0.071,7 016003.43666 0.00454
21,-1,3,4,7,Be,,15768.999 0.071,5371.548 0.010,B- -11907.551 25.150,7 016928.717 0.076
22,-3,2,5,7,B,p4n,27676.550 25.150,3558.705 3.593,B- *,7 029712.000 27.000
23,0 4,6,2,8,He,,31609.681 0.089,3924.520 0.011,B- 10663.878 0.100,8 033934.390 0.095
24,2,5,3,8,Li,,20945.804 0.047,5159.712 0.006,B- 16004.133 0.059,8 022486.246 0.050
25,0,4,4,8,Be,-a,4941.671 0.035,7062.435 0.004,B- -17979.896 1.000,8 005305.102 0.037
26,-2,3,5,8,B,,22921.567 1.000,4717.155 0.125,B- -12142.701 18.270,8 024607.316 1.073
27,-4,2,6,8,C,,35064.268 18.243,3101.524 2.280,B- *,8 037643.042 19.584
28,0 5,7,2,9,He,,40935.826 46.816,3349.037 5.202,B- 15980.924 46.817,9 043946.419 50.259
29,3,6,3,9,Li,-3n,24954.902 0.186,5037.768 0.021,B- 13606.449 0.201,9 026790.191 0.200
...,...,...,...,...,...,...,...,...,...,...
3406,57,170 1,13 2,283,Ed,-a,164707# 436#,7177# 2#,B- * 2,83 176820# 468#
3407,0 60,172 1,12 2,284,Cn,-a,162545# 806#,7190# 3#,B- -4046# 966# 2,84 174499# 865#
3408,58,171 1,13 2,284,Ed,-a,166591# 534#,7173# 2#,B- -2330# 846# 2,84 178843# 573#
3409,56,170 1,14 2,284,Fl,-a,168921# 656#,7162# 2#,B- * 2,84 181344# 704#
3410,0 61,173 1,12 2,285,Cn,-a,165173# 581#,7184# 2#,B- -2557# 995# 2,85 177321# 624#
3411,59,172 1,13 2,285,Ed,-a,167731# 807#,7173# 3#,B- -3272# 897# 2,85 180066# 866#
3412,57,171 1,14 2,285,Fl,-a,171003# 391#,7158# 1#,B- * 2,85 183579# 419#
3413,0 60,173 1,13 2,286,Ed,-a,170014# 656#,7168# 2#,B- -1758# 928# 2,86 182518# 704#
3414,58,172 1,14 2,286,Fl,-a,171773# 657#,7159# 2#,B- * 2,86 184406# 705#
3415,0 61,174 1,13 2,287,Ed,-a,171245# 725#,7167# 3#,B- -2827# 948# 2,87 183840# 778#
3416,59,173 1,14 2,287,Fl,-a,174073# 610#,7154# 2#,B- -3823# 752# 2,87 186875# 655#
3417,57,172 1,15 2,287,Ef,-a,177895# 439#,7138# 2#,B- * 2,87 190978# 471#
3418,0 60,174 1,14 2,288,Fl,-a,175042# 806#,7154# 3#,B- -4728# 968# 2,88 187916# 865#
3419,58,173 1,15 2,288,Ef,-a,179771# 536#,7135# 2#,B- * 2,88 192992# 576#
3420,0 61,175 1,14 2,289,Fl,-a,177564# 584#,7148# 2#,B- -3102# 997# 2,89 190623# 626#
3421,59,174 1,15 2,289,Ef,-a,180666# 809#,7135# 3#,B- -3861# 947# 2,89 193953# 868#
3422,57,173 1,16 2,289,Lv,-a,184528# 492#,7119# 2#,B- * 2,89 198099# 529#
3423,0 60,175 1,15 2,290,Ef,-a,182894# 658#,7130# 2#,B- -2304# 932# 2,90 196345# 706#
3424,58,174 1,16 2,290,Lv,-a,185198# 660#,7120# 2#,B- * 2,90 198818# 708#
3425,0 61,176 1,15 2,291,Ef,-a,183990# 784#,7130# 3#,B- -3397# 995# 2,91 197522# 842#
3426,59,175 1,16 2,291,Lv,-a,187387# 612#,7116# 2#,B- -4413# 853# 2,91 201169# 658#
3427,57,174 1,17 2,291,Eh,-a,191800# 594#,7098# 2#,B- * 2,91 205906# 637#
3428,0 60,176 1,16 2,292,Lv,-a,188242# 806#,7116# 3#,B- -5334# 1047# 2,92 202086# 865#
3429,58,175 1,17 2,292,Eh,-a,193576# 669#,7095# 2#,B- * 2,92 207812# 718#
3430,0 61,177 1,16 2,293,Lv,-a,190669# 586#,7111# 2#,B- -3716# 1000# 2,93 204691# 629#
3431,59,176 1,17 2,293,Eh,-a,194385# 810#,7095# 3#,B- -4488# 1072# 2,93 208680# 870#
3432,57,175 1,18 2,293,Ei,-a,198873# 702#,7077# 2#,B- * 2,93 213498# 753#
3433,0 60,177 1,17 2,294,Eh,-a,196521# 660#,7092# 2#,B- -2942# 936# 2,94 210974# 708#
3434,58,176 1,18 2,294,Ei,-a,199463# 663#,7079# 2#,B- * 2,94 214132# 712#
3435,0 59,177 1,18 2,295,Ei,-a,201512# 644#,7075# 2#,B- * 2,95 216332# 692#

In [4]:
def search(element) :
    print(df.loc[df['EL'] == element])

## Searching Values
The column 'A' represents the atomic number. In the next code block this column is searched through. To search for a particular atomic number the number 3 must be changed to whatever atomic number you want to look for.

The column 'EL' represents the element. Two code blocks down this column is searched through. To search through it you must enter the element's symbol you want to look for where Al is right now.

In [5]:
df.loc[df['A'] == '3']

,1N-Z,N,Z,A,EL,O,MASS EXCESS,BINDING ENERGY/A,BETA-DECAY ENERGY,ATOMIC MASS
3,0 1,2,1,3,H,,14949.80993 0.00022,2827.265 0.000,B- 18.592 0.000,3 016049.28199 0.00023
4,-1,1,2,3,He,,14931.21793 0.00021,2572.680 0.000,B- -13736# 2000#,3 016029.32265 0.00022
5,-3,0,3,3,Li,-pp,28667# 2000#,-2267# 667#,B- *,3 030775# 2147#

In [11]:
df.loc[df['EL'] == 'Al']

,1N-Z,N,Z,A,EL,O,MASS EXCESS,BINDING ENERGY/A,BETA-DECAY ENERGY,ATOMIC MASS
114,-5,8,13,21,Al,x,26990# 596#,6302# 28#,B- *,21 028975# 640#
122,-4,9,13,22,Al,x,18201# 401#,6782# 18#,B- -15137# 643#,22 019540# 430#
131,-3,10,13,23,Al,--,6748.070 0.345,7335.727 0.015,B- -16949# 503#,23 007244.351 0.370
139,-2,11,13,24,Al,ep,-48.865 0.233,7649.582 0.010,B- -10794.060 19.473,23 999947.541 0.250
148,-1,12,13,25,Al,,-8915.975 0.065,8021.136 0.003,B- -12743.299 10.000,24 990428.306 0.069
156,0,13,13,26,Al,,-12210.151 0.067,8149.765 0.003,B- -5069.136 0.085,25 986891.863 0.071
165,1,14,13,27,Al,,-17196.861 0.047,8331.553 0.002,B- -4812.359 0.096,26 981538.408 0.050
174,2,15,13,28,Al,-n,-16850.645 0.077,8309.894 0.003,B- 4642.150 0.077,27 981910.087 0.083
183,3,16,13,29,Al,x,-18207.760 0.345,8348.464 0.012,B- 3687.318 0.345,28 980453.164 0.370
192,4,17,13,30,Al,x,-15864.844 2.888,8261.128 0.096,B- 8568.116 2.888,29 982968.388 3.100
202,5,18,13,31,Al,x,-14950.706 2.236,8225.517 0.072,B- 7998.330 2.236,30 983949.756 2.400
211,6,19,13,32,Al,x,-11099.367 7.173,8100.344 0.224,B- 12978.319 7.179,31 988084.339 7.700
221,7,20,13,33,Al,x,-8497.380 6.986,8020.616 0.212,B- 12016.945 7.021,32 990877.687 7.500
231,8,21,13,34,Al,x,-3000.289 3.074,7860.428 0.090,B- 16956.563 14.448,33 996779.057 3.300
241,9,22,13,35,Al,x,-223.728 7.359,7787.124 0.210,B- 14167.729 36.605,34 999759.817 7.900
251,10,23,13,36,Al,x,5950.384 149.505,7623.515 4.153,B- 18386.508 165.851,36 006388.000 160.500
262,11,24,13,37,Al,x,9809.563 180.244,7531.315 4.871,B- 16381.075 213.168,37 010531.000 193.500
272,12,25,13,38,Al,x,16209.859 374.461,7377.097 9.854,B- 20380.157 388.847,38 017402.000 402.000
283,13,26,13,39,Al,x,20650# 400#,7281# 10#,B- 18330# 422#,39 022169# 429#
294,14,27,13,40,Al,x,27590# 400#,7127# 10#,B- 22160# 528#,40 029619# 429#
305,0 15,28,13,41,Al,x,33420# 500#,7008# 12#,B- 21300# 747#,41 035878# 537#
316,0 16,29,13,42,Al,x,40100# 600#,6874# 14#,B- 23630# 781#,42 043049# 644#
328,0 17,30,13,43,Al,x,47020# 800#,6741# 19#,B- 23919# 998#,43 050478# 859#